#!/usr/bin/env node
import chalk from 'chalk';
console.log()
console.log(chalk.bgBlack('            version  1.1.7-beta            '))
console.log()
console.log(chalk.bgBlue("                 Front-End                 ")) 
console.log('')
console.log(' -----------------------------------------')
console.log('|        name         ' + ' | last update      |')
console.log('|-----------------------------------------|')
console.log('|      ReactTS        ' + ' | 17/02/66         |')
console.log('|      SolidTS        ' + ' | 17/02/66         |')
console.log(' -----------------------------------------')
console.log('')
console.log(chalk.bgRed("                 Back-End                  ")) 
console.log('')
console.log(' -----------------------------------------')
console.log('|        name         ' + '   | last update    |')
console.log('|-----------------------------------------|')
console.log('| Actix-web + MongoDB   ' + ' | 07/05/66       |')
console.log('| Actix-web + PostgreSQL' + ' | --/--/--       |')
console.log('| ExpressTS + MongoDB   ' + ' | 17/02/66       |')
console.log('| ExpressTS + PostgreSQL' + ' | --/--/--       |')
console.log(' -----------------------------------------')
console.log('')
console.log(chalk.bgGreen("              Mobile Desktop               ")) 
console.log('')
console.log(' -----------------------------------------')
console.log('|        name         ' + '   | last update    |')
console.log('|-----------------------------------------|')
console.log('| Tauri Mobile         ' + '  | --/--/--       |')
console.log('| Tauri Desktop        ' + '  | 17/02/66       |')
console.log(' -----------------------------------------')
console.log('')

